test

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -56,13 +56,13 @@ jobs:
          run: terraform plan -no-color -input=false -out planfile
          continue-on-error: true
 
-       - name: Terraform plan status
-         if: steps.plan.outcome == 'failure' 
-         run: exit 1     
+      #  - name: Terraform plan status
+      #    if: steps.plan.outcome == 'failure' 
+      #    run: exit 1     
 
        - name: Terraform Apply
          id: apple
-         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+        #  if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          run: terraform apply -auto-approve -input=false -parallelism=1 planfile
 
        - name: Configure AWS credentials
@@ -74,7 +74,7 @@ jobs:
      
        - name: Get Kube config file
          id: getconfig
-         if: steps.apple.outcome == 'success'
+        #  if: steps.apple.outcome == 'success'
          run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }} 
 
        - name: Install Ingress controller
